---

mde_org_id: ''
# mde_healthy: true
# set to false as test environment and no license
mde_healthy: false
mde_tags: ''
mde_proxy_host: ''
mde_proxy_port: ''
mde_version: '101.62'
mde_managed: false
mde_passive_mode_enabled: false
